version: '3.8'

services:
  tailscale:
    build:
      context: .
      dockerfile: Dockerfile.tailscale
    container_name: tailscale-exit-node
    hostname: docker-hole
    privileged: true
    volumes:
      - ./tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-exit-node --accept-dns=false
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    network_mode: service:tailscale
    environment:
      - TZ=${TZ:-UTC}
      - WEBPASSWORD=${PIHOLE_PASSWORD}
      - FTLCONF_dns_upstreams=1.1.1.1;8.8.8.8
      - FTLCONF_dns_listeningMode=ALL # Required to accept redirected traffic
      - FTLCONF_resolver_resolveIPv6=false
      - FTLCONF_dns_rateLimit_count=0
      - FTLCONF_dns_rateLimit_interval=0
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
